name: ESLint Check

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint and Save Output
      run: |
        npx eslint "src/**/*.ts" --format json > eslint-report.json || exit 0

    - name: Check ESLint Output
      run: cat eslint-report.json  # Ensure valid JSON is produced

    - name: Run Reviewdog with ESLint Output
      uses: reviewdog/action-eslint@v1
      with:
        reporter: 'github-pr-review'
        level: 'error'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        eslint_flags: '--format json eslint-report.json'
        filter_mode: 'added'
