name: ESLint Check

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --format json --output-file eslint-report.json || true

      - name: ReviewDog - Report ESLint Suggestions
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.ESLINT_TOKEN }}
          level: info # Show both warnings and errors
          reporter: github-pr-review # Post comments in the PR
          fail_level: warning # Ensure workflow doesn't stop on errors
          filter_mode: added # Only show comments on added/modified lines

      - name: Check for ESLint errors & add label
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TOTAL_ERRORS=$(jq '[.[] | .errorCount] | add' eslint-report.json)
          echo "Total Errors: $TOTAL_ERRORS"
          if [ "$TOTAL_ERRORS" -gt 0 ]; then
            echo "ESLint found $TOTAL_ERRORS errors."
            gh pr edit ${{ github.event.pull_request.number }} --add-label "eslint-errors"
            exit 1
          else
            echo "No ESLint errors found."
          fi
