name: ESLint Check

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint
      id: eslint
      run: |
        npx eslint "src/**/*.ts" --format json > eslint-report.json || exit 0

    - name: Run Reviewdog
      uses: reviewdog/action-eslint@v1
      with:
        reporter: 'github-pr-review'
        level: 'error'
        eslint_flags: '--format json'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        filter_mode: 'added'
