name: ESLint Check

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Grant write permissions to post comments

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint with Reviewdog
      uses: reviewdog/action-eslint@v1
      with:
        reporter: 'github-pr-review'
        level: 'error'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        eslint_flags: '--format json'
        filter_mode: 'added'