name: ESLint Check

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint and Convert Output to rdjson
      run: |
        npx eslint "src/**/*.ts" --format json | jq -c '{source: "eslint", diagnostics: .}' > eslint-report.rdjson || exit 0

    - name: Check rdjson Output
      run: cat eslint-report.rdjson

    - name: Run Reviewdog with ESLint Output
      uses: reviewdog/action-eslint@v1
      with:
        reporter: 'github-pr-review'
        level: 'error'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        input: eslint-report.rdjson
        filter_mode: 'added'
