name: ESLint Check

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --format json --output-file eslint-report.json || true

      - name: ReviewDog - Report ESLint Suggestions
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: info  # Displays both warnings and errors
          reporter: github-pr-review  # Posts comments in the PR
          fail_on_error: false  # Prevents workflow failure on errors
          filter_mode: added  # Comments only on modified/added lines