name: Deploy NestJS App to EC2

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build the app
      run: npm run build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd sada-khata-backend
          git pull origin main
          npm install
          npm run build

          echo "${{ secrets.MAIN_ENV }}" > .env

          cd ..
          pm2 restart ecosystem.config.js
